### PR TITLE
ICLA timja

### PR DESCRIPTION
**Pull request by timja**
@oleg-nenashev @rtyler @slide @uhafner

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I need to verify the PDF before merging. Reached out to other board members to get access to private keys

**Comment by rtyler** [comment]
I'm merging, to be honest @oleg-nenashev I've not been bothering to verify the signatures. Just having them, with this PR originating from a github account,  is enough from my perspective

**Comment by slide** [comment]
Is this something we could automate? I know the dotnet foundation has CLA automation on gh

**Comment by oleg-nenashev** [comment]
@slide We could. There is an open question about future of CLA after the migration to CDF. My assumption is that we **might** need to refresh CLAs for everybody, because now it explicitly references SPI. I do not care too much about it, but we need to be ready to requirements from CDF/LF on these fronts (legal matters, huh?)

**Comment by slide** [comment]
@oleg-nenashev Yeah, all the legal stuff currently goes over my head, but I should probably learn more about it.

**Pull request merged**
