### PR TITLE
[eax] fix my CLA

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by grimreaper** [comment]
@daniel-beck is this sufficient ?

**Comment by daniel-beck** [comment]
It's not obviously broken. I cannot view the submitted file though.

**Comment by grimreaper** [comment]
I generated it using 
"gpg --local-user eitan@eitanadler.com --encrypt --sign --armor -r "Jenkins Project CLA" < icla.pdf >| cla.pdf.asc"

Rerunning that gives different output. Does #71 help?

**Comment by daniel-beck** [comment]
To clarify, I don't have the private key to view contents. All I can review is the public stuff.

**Comment by grimreaper** [comment]
@rtyler can I help anything? What will take to finish the process?

**Comment by daniel-beck** [comment]
Not sure about the first two, but for the third, the documentation does not reflect our current practices. We're still happy to add new contributors, but given how easy the PR model of GitHub makes it to contribute even without commit access, it makes more sense to go through that first. That way more experienced contributors can provide feedback, and you can get accustomed to our development and release process.

**Comment by batmat** [comment]
I agree with Daniel here. Giving core merge access probably requires one to have at least gone through the process of modifying the core first a few times through PRs (because, well, **anyway** this is the only way we modify the core. Pushing directly would be seen as a major mishaps).

Looking at https://github.com/jenkinsci/jenkins/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Agrimreaper+, correct me if I'm wrong, but does not seem like you already file a first PR. So, I think it's not time yet to add you to @jenkinsci/core and provide access to merging PRs in all Jenkins core components.

**Comment by batmat** [comment]
@grimreaper also, more generally, to help people/reviewers go faster, and help you save time too in the process: providing a description in your PR explaining what is your goal here would help understand the purpose here.

**Pull request merged**
