### PR TITLE
Add Baptiste Mathus ICLA

### PR DESCRIPTION
**Pull request by batmat**

### CODE REVIEW

**Comment by batmat** [comment]
Ping @kohsuke and happy FOSDEM :)

**Comment by batmat** [comment]
ping @rtyler as you're also in the board :) (granted https://wiki.jenkins-ci.org/display/JENKINS/Governance+Board should be up-to-date since he was updated a few days ago)

**Comment by batmat** [comment]
Thanks Tyler.

2016-02-01 15:14 GMT+00:00 R. Tyler Croy <notifications@github.com>:

**Comment by batmat** [comment]
@rtyler @kohsuke re-read https://wiki.jenkins-ci.org/display/JENKINS/Governance+Document#GovernanceDocument-Corecommitters what am I missing to have push/merge permission on jenkinsci/jenkins?

Thanks

**Comment by rtyler** [comment]
@batmat I don't understand what you're asking, are you missing commit access?

**Comment by batmat** [comment]
@rtyler yes. "Missing" might be too strong, indeed I don't absolutely/strictly need it, sure. But having commit access  on core might help in some cases going forward.
But if we want to keep the number of people having that permission not too high to reduce risk, I can understand too.

**Comment by batmat** [comment]
Ping @daniel-beck :)
```
[06:35] <      rtyler> | batmat: when you see danielbeck pop onto the channel, make him give you commit access
[06:35] <@     rtyler> | I'm too sleepy
[06:35] <@     rtyler> | :)
```

**Pull request merged**
