### PR TITLE
Adding committer.properties

### PR DESCRIPTION
**Pull request by vsilverman**
Preparing for signing CLA doc

### CODE REVIEW

**Comment by rtyler** [comment]
@vsilverman do you plan on actually signing things soon? :smile_cat:

**Comment by vsilverman** [comment]
PR #90 is submitted to address outstanding CLA issue

**Comment by vsilverman** [comment]
@rtyler Thanks for reminding, you may see https://github.com/jenkinsci/infra-cla/pull/90 <https://github.com/jenkinsci/infra-cla/pull/90>

**Comment by oleg-nenashev** [comment]
Closing in favor of the merged PR

**Pull request closed without merging**
