### PR TITLE
chore: add ICLA for Hervé Le Meur

### PR DESCRIPTION
**Pull request by lemeurherve**

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by lemeurherve** [comment]
@oleg-nenashev I've seen in the Jenkins Governance Meeting notes that I was missing the ICLA, thus this PR to add it :)

**Comment by MarkEWaite** [comment]
@oleg-nenashev and @halkeye I am not yet a member of the https://github.com/orgs/jenkinsci/teams/board .  I assume I should be a member of that team?

**Comment by halkeye** [comment]
> @oleg-nenashev and @halkeye I am not yet a member of the https://github.com/orgs/jenkinsci/teams/board . I assume I should be a member of that team?

yea, I only knew about the jenkins-infra team, I'm requesting access to the jenkinsci team so I can get that fixed.

**Comment by halkeye** [comment]
afaik only kk, @oleg-nenashev and @uhafner currently have the ability to decode CLAs so they can get reviewed. or at least I can't.

**Comment by timja** [comment]
No one actually reviews them @halkeye, Tyler was just merging them as long as someone submitted via GitHub with their own GitHub account taking the GitHub audit record

https://github.com/jenkinsci/infra-cla/pull/81#issuecomment-577382488

**Review by timja — APPROVED** [review]

**Comment by halkeye** [comment]
with tim's comment about not actually decoding them, I'll merge

**Comment by oleg-nenashev** [comment]
I can add the rest of the board to the signing certificate. FWIW I always wanted to get rid of this impediment, hence did not bother too much to review the encrypted certs too

**Pull request merged**
